#!/usr/bin/env bash
# Installs Nginx

sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx stop
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
