#!/bin/bash
# Ensure Nginx is installed
sudo apt-get update
sudo apt-get install -y nginx

# Write redirection directly ensuring no syntax errors
echo "location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }" | sudo tee /etc/nginx/conf.d/redirect_me.conf

# Test configuration and reload Nginx
sudo nginx -t && sudo service nginx reload
