#!/usr/bin/env bash
# Installs nginx web server

apt-get update
apt-get install -y nginx
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=NEy6Oj8dmCc&ab_channel=NewMediaAcademyLife;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
