#!/usr/bin/env bash
# Bash script that displays Best School 10 times.
count=0
while [ $count -lt 10 ]
    do
        if [ $count -eq 9 ]; then
            echo "Hi"
			echo "Best School"
        else
            echo "Best School"
        fi

		((count++))
            
    done
