#!/usr/bin/env bash
# Bash script that displays The content of the current directory

for i in *
do
    echo $i | cut -d'-' -f2-
done

# #!/usr/bin/env bash
# # displays the content of the current working directory.

# for i in *
# 	do
#     	echo "$i" | cut -d'-' -f2
# 	done